### ISSUE TITLE
Project 2.4 Colorful light - Orange? Negative...

### ISSUE THREAD

**Issue by anglerfish27** [sunfounder/kepler-kit#4]
I found that this program works fine in terms of execution. However based on the values set in the example and the document which shows that red at 255 and green at 128 with blue  at 0 gives you orange.
[https://docs.sunfounder.com/projects/kepler-kit/en/latest/pyproject/py_rgb.html](url)

I've messed around with the inputs, I can get a solid green, red or blue by setting them to 255,0,0 0,255,0 0,0,255 ect..
I'm using the right resistors, verified using my bench top DMM, the resistances are all within tolerances.

The color given off by running this example is more of a greenish/yellowish color, nothing even close to the documentation (orange). I found if i set things to 255,10,0 then I get something that looks more like Orange.

I tried using one of my own CC RGB LED's same result.
While I'm new to Micropython, I am not new to Pico programming, I have made many complex programs with pure C (not Arduino) and the SDK in VSC, 

This is more of either a correction that needs to be made in the training documentation. If someone is using this kit that has zero experience to any programming and Pico/W this example would leave them wondering what they did wrong because they are not getting an orange like the documentation.

For the sake of sanity because I'm human and prone to errors I even tried a copy paste of the code from github. No change. My handwritten code matches 100%.

I thought it was quality control on the LED, but as I stated I tried my own that are of higher quality and all result in this greenish yellow color that does not look Orange. Maybe edit the code to have the user try, just red, then just green, and then just blue. Then let them mix them on their own with no expectation of an Orange at 255,128,0

Anyways just a thought. Trying to help when I can. The documentation shows a nice Orange for 255,128,0 which is NOT the case at all. So far the Kepler kit has been great no issues. Very similar components and projects that I purchased from a different vendor to learn pure C.  I love C programming and its speed but boy MP makes life so much easier for writing code hence I came to the dark side! Mostly for the Wifi. Wifi in pure C is rough...oof.

Cheers,
Anglerfish

**Comment by eMUQI** [comment]
Hi, @anglerfish27 

Thank you for your detailed feedback and observations regarding the RGB color values in the SunFounder Kepler kit documentation. It's great to see your dedication to ensuring accuracy and helping others in the community. I understand your concern about the color output not matching the documentation, even though the RGB values seem correct.

The RGB values of 255, 128, 0 should indeed result in an orange color based on standard color theory. You can also preview this on [this webpage](https://www.w3schools.com/colors/colors_rgb.asp) by inputting 255, 128, 0.

![orange](https://github.com/sunfounder/kepler-kit/assets/32332228/911e47af-200a-4819-8702-7767ba34f297)

However, you've mentioned that the actual color output is more greenish/yellowish. There could be several reasons for this discrepancy:

1. **Hardware Differences:** RGB LED modules can vary in quality and behavior. The color output may not always match the ideal RGB values due to variations in LED manufacturing or driver circuitry. This could explain why your higher-quality RGB LEDs also produce a similar result. The LED included in the kit is intended for educational purposes and may not display colors accurately.

2. **LED Characteristics:** The LED's forward voltage, current, and luminance characteristics can impact the perceived color. LEDs with different specifications might not respond exactly as expected to the given RGB values.

Thank you for sharing your insights, and I hope this helps you and others in the community achieve the desired color results with RGB LEDs in the Kepler kit or similar projects. If you have any more questions or need further assistance, feel free to ask. Good luck with your MicroPython projects!
